[package]
authors = ["rmyhovych <rmyhovych@gmail.com>"]
edition = "2018"
name = "tenso-rs"
version = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
rand = "0.6.5"

[dev-dependencies]
plotters = "^0.3.0"